# Generated by Django 3.1.2 on 2020-11-17 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dup10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
