# Generated by Django 3.1.2 on 2020-11-20 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dup10', '0002_flower_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='flower',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 6, 14, 24, 247211)),
        ),
    ]
