# Generated by Django 3.1.2 on 2020-11-20 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dup10', '0003_auto_20201120_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='flower',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 6, 20, 23, 218653)),
        ),
    ]
