# Generated by Django 3.1.2 on 2020-11-20 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dup10', '0004_auto_20201120_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 13, 0, 22, 369974)),
        ),
    ]
