# Generated by Django 3.1.2 on 2020-11-21 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dup10', '0005_auto_20201120_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 6, 7, 44, 81697)),
        ),
    ]
