# Generated by Django 3.1.2 on 2020-11-21 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dup10', '0006_auto_20201121_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.AlterField(
            model_name='flower',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 6, 15, 54, 331536)),
        ),
    ]
